---
- name: install Wazuh agent on workstations
  hosts: ADworkstations
  become: True
  become_user: root
  become_method: sudo
  vars:
    hostname: 

  tasks:
    - name: install agent
      shell: |
        wget -4 https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.0-1_amd64.deb && sudo WAZUH_MANAGER='10.0.8.20' WAZUH_AGENT_NAME='{{ hostname }}' WAZUH_AGENT_GROUP='workstation' dpkg -i ./wazuh-agent_4.10.0-1_amd64.deb
      args:
        executable: /bin/bash
    
    - name: enable/start agent
      shell: |
        sudo systemctl daemon-reload
        sudo systemctl enable wazuh-agent
        sudo systemctl start wazuh-agent
      args:
        executable: /bin/bash