name: deploy to production server
on:
  push:
    branches:
      - test
jobs:
  image:
    runs-on: ubuntu-latest 
    steps:
      - name: Install Python
        run: |
          apt-get update 
          apt-get install -y python3 python3-pip  

      # - name: Install Nodejs
      #   run: |
      #     apt-get install nodejs -y
      #     apt-get install npm -y   

      - name: Install docker
        run: |
          apt install docker.io docker-compose -y

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker --no-cache build -t nj112/moodle:latest .
          docker push nj112/moodle:latest
