authentication.fallback-admin.secret = "$6$N.7FvAld5hgWigQ5$tlfSgZ4jLKTTlqKWpP5RbYOZQgraund/1qlCi5lxguLvf01MOtmx9K6GSz6uOXw5zk1DMJYsGPhE/SWgALuaX1"
authentication.fallback-admin.user = "admin"
directory.internal.store = "rocksdb"
directory.internal.type = "internal"
directory.openldap.attributes.class = "objectClass"
directory.openldap.attributes.description = "description"
directory.openldap.attributes.email = "mail"
directory.openldap.attributes.email-alias = "mailAlias"
directory.openldap.attributes.groups = "memberOf"
directory.openldap.attributes.name = "uid"
directory.openldap.attributes.quota = "diskQuota"
directory.openldap.attributes.secret = "userPassword"
directory.openldap.base-dn = "dc=radius,dc=ijsselstreek-university,dc=nl"
directory.openldap.bind.auth.enable = false
directory.openldap.bind.dn = "cn=admin,dc=radius,dc=ijsselstreek-university,dc=nl"
directory.openldap.bind.secret = "Welkom123"
directory.openldap.cache.entries = 500
directory.openldap.cache.ttl.negative = "10m"
directory.openldap.cache.ttl.positive = "1h"
directory.openldap.filter.domains = "(&(|(objectClass=posixAccount)(objectClass=posixGroup))(|(mail=*@?)(mailAlias=*@?)))"
directory.openldap.filter.email = "(&(|(objectClass=posixAccount)(objectClass=posixGroup))(|(mail=?)(mailAlias=?)(mailList=?)))"
directory.openldap.filter.expand = "(&(|(objectClass=posixAccount)(objectClass=posixGroup))(mailList=?))"
directory.openldap.filter.name = "(&(|(objectClass=posixAccount)(objectClass=posixGroup))(uid=?))"
directory.openldap.filter.verify = "(&(|(objectClass=posixAccount)(objectClass=posixGroup))(|(mail=*?*)(mailAlias=*?*)))"
directory.openldap.timeout = "15s"
directory.openldap.tls.allow-invalid-certs = false
directory.openldap.tls.enable = false
directory.openldap.type = "ldap"
directory.openldap.url = "ldap://ldap.ijsselstreek-university.nl:389"
lookup.default.hostname = "server7"
server.auto-ban.abuse.rate = false
server.auto-ban.auth.rate = false
server.auto-ban.loiter.rate = false
server.auto-ban.scan.paths.00 = "*.php*"
server.auto-ban.scan.paths.01 = "*.cgi*"
server.auto-ban.scan.paths.02 = "*.asp*"
server.auto-ban.scan.paths.03 = "*/wp-*"
server.auto-ban.scan.paths.04 = "*/php*"
server.auto-ban.scan.paths.05 = "*/cgi-bin*"
server.auto-ban.scan.paths.06 = "*xmlrpc*"
server.auto-ban.scan.paths.07 = "*../*"
server.auto-ban.scan.paths.08 = "*/..*"
server.auto-ban.scan.paths.09 = "*joomla*"
server.auto-ban.scan.paths.10 = "*wordpress*"
server.auto-ban.scan.paths.11 = "*drupal*"
server.auto-ban.scan.rate = false
server.listener.http.bind = "[::]:8080"
server.listener.http.protocol = "http"
server.listener.https.bind = "[::]:443"
server.listener.https.protocol = "http"
server.listener.https.tls.implicit = true
server.listener.imap.bind = "[::]:143"
server.listener.imap.protocol = "imap"
server.listener.imaptls.bind = "[::]:993"
server.listener.imaptls.protocol = "imap"
server.listener.imaptls.tls.implicit = true
server.listener.pop3.bind = "[::]:110"
server.listener.pop3.protocol = "pop3"
server.listener.pop3s.bind = "[::]:995"
server.listener.pop3s.protocol = "pop3"
server.listener.pop3s.tls.implicit = true
server.listener.sieve.bind = "[::]:4190"
server.listener.sieve.protocol = "managesieve"
server.listener.smtp.bind = "[::]:25"
server.listener.smtp.protocol = "smtp"
server.listener.submission.bind = "[::]:587"
server.listener.submission.protocol = "smtp"
server.listener.submissions.bind = "[::]:465"
server.listener.submissions.protocol = "smtp"
server.listener.submissions.tls.implicit = true
storage.blob = "rocksdb"
storage.data = "rocksdb"
storage.directory = "openldap"
storage.fts = "rocksdb"
storage.lookup = "rocksdb"
store.rocksdb.compression = "lz4"
store.rocksdb.path = "/etc/stalwart/data"
store.rocksdb.type = "rocksdb"
tracer.log.ansi = false
tracer.log.enable = true
tracer.log.level = "info"
tracer.log.path = "/etc/stalwart/logs"
tracer.log.prefix = "stalwart.log"
tracer.log.rotate = "daily"
tracer.log.type = "log"