- name: Instaleer ClamAV
  hosts: all
  become: true

  tasks:
    - name: Update de package cache
      apt:
        update_cache: yes

    - name: Instaleer ClamAV and ClamAV Daemon
      apt:
        name:
          - clamav
          - clamav-daemon
        state: present

    - name: Start ClamAV service
      systemd:
        name: clamav-daemon
        enabled: yes
        state: started
