---
- name: Install Moodle and configure the environment 
  hosts: localhost
  become: true
  vars:
    localip: "192.168.109.146" # The local IP of de VM

  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add Ondrej PHP repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP 7.4 and required extensions
      apt:
        name:
          - php7.4
          - php7.4-pspell
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
          - php7.4-mysql
          - php7.4-xml
          - php7.4-xmlrpc
          - php7.4-ldap
          - php7.4-zip
          - php7.4-soap
          - php7.4-mbstring
        state: present

    - name: Set preference PHP-version to 7.4
      ansible.builtin.shell: sudo update-alternatives --set php /usr/bin/php7.4

    - name: Install Apache, MySQL, and additional PHP modules
      apt:
        name:
          - apache2
          - mysql-client
          - mysql-server
          - libapache2-mod-php
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

    - name: Clone Moodle repository
      git:
        repo: git://git.moodle.org/moodle.git
        dest: /opt/moodle
        version: MOODLE_400_STABLE
        track_submodules: yes

    - name: Copy Moodle to web server directory
      copy:
        src: /opt/moodle
        dest: /var/www/html
        remote_src: yes

    - name: Create directory /var/moodledata
      ansible.builtin.shell: sudo mkdir /var/moodledata

    - name: Set permissions for /var/moodledata
      ansible.builtin.shell: sudo chown -R www-data /var/moodledata

    - name: Set permissions for /var/www
      ansible.builtin.shell: sudo chmod -R 777 /var/www

    - name: Set permissions for /var/moodledata
      ansible.builtin.shell: sudo chmod -R 777 /var/moodledata

    - name: Set permissions for config.php
      ansible.builtin.shell: sudo chmod -R 0755 /var/www/html/moodle

    - name: Run the MySQL setup script
      script: bash/mysql.sh

    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted

    - name: Create Moodle config.php file
      copy:
        dest: /var/www/html/moodle/config.php
        content: |
          <?php  // Moodle configuration file

          unset($CFG);
          global $CFG;
          $CFG = new stdClass();

          $CFG->dbtype    = 'mysqli';
          $CFG->dblibrary = 'native';
          $CFG->dbhost    = 'localhost';
          $CFG->dbname    = 'moodle';
          $CFG->dbuser    = 'pcgebruiker';
          $CFG->dbpass    = 'Welkom123';
          $CFG->prefix    = 'mdl_';
          $CFG->dboptions = array (
            'dbpersist' => 0,
            'dbport' => '',
            'dbsocket' => '',
            'dbcollation' => 'utf8mb4_unicode_ci',
          );

          $CFG->wwwroot   = 'http://{{ localip }}/moodle';
          $CFG->dataroot  = '/var/moodledata';
          $CFG->admin     = 'admin';

          $CFG->directorypermissions = 0777;

          require_once(__DIR__ . '/lib/setup.php');

          // There is no php closing tag in this file,
          // it is intentional because it prevents trailing whitespace problems!

    - name: Create Moodle 000-default.conf file (Apache config file)
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>

                  ServerAdmin webmaster@localhost
                  DocumentRoot /var/www/html

                  ErrorLog ${APACHE_LOG_DIR}/error.log
                  CustomLog ${APACHE_LOG_DIR}/access.log combined

                  # Added

                  RedirectMatch "^/$" "/moodle" 

          </VirtualHost>

    - name: Restart apache2
      ansible.builtin.shell: sudo systemctl restart apache2

    - name: Launch install
      ansible.builtin.shell: sudo php /var/www/html/moodle/admin/cli/install_database.php --adminuser=pcgebruiker --adminpass=Welkom123 --adminemail=testmail@test.nl --agree-license

    - name: Create course.csv
      copy:
        dest: /var/www/html/moodle/admin/tool/uploadcourse/cli/course.csv
        content: |
          shortname,fullname,category
          4.1,NSE periode 1,1
          4.2,NSE periode 2,1
          4.3,NSE periode 3,1
          4.4,NSE periode 4,1

    - name: Create users.csv
      copy:
        dest: /var/www/html/moodle/admin/tool/uploaduser/cli/users.csv
        content: |
          username,password,firstname,lastname,email,course1,role1,course2,role2,course3,role3,course4,role4
          pcgebruiker1,Welkom123,pcgebruiker1,editingteacher,pcgebruiker1@test.com,4.1,editingteacher,4.2,editingteacher,4.3,editingteacher,4.4,editingteacher
          pcgebruiker2,Welkom123,pcgebruiker2,student,pcgebruiker2@test.com,4.1,student,4.2,student,4.3,student,4.4,student
          pcgebruiker3,Welkom123,pcgebruiker3,manager,pcgebruiker3@test.com,4.1,manager,4.2,manager,4.3,manager,4.4,manager
          pcgebruiker4,Welkom123,pcgebruiker4,student,pcgebruiker4@test.com,4.1,student,4.2,student,4.3,student,4.4,student

    - name: Launch create course
      ansible.builtin.shell: php uploadcourse.php --file=course.csv -m=createorupdate -u=missingonly --allowdeletes --allowrenames --allowresets
      args:
        chdir: /var/www/html/moodle/admin/tool/uploadcourse/cli

    - name: Launch create users
      ansible.builtin.shell: php uploaduser.php --file=users.csv --uuforcepasswordchange=0
      args:
        chdir: /var/www/html/moodle/admin/tool/uploaduser/cli
