---
- name: Install Moodle and configure the environment
  hosts: localhost
  become: true
  tasks:
    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present
        update_cache: yes

    - name: Add Ondrej PHP repository
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP 7.4 and required extensions
      apt:
        name:
          - php7.4
          - php7.4-pspell
          - php7.4-curl
          - php7.4-gd
          - php7.4-intl
          - php7.4-mysql
          - php7.4-xml
          - php7.4-xmlrpc
          - php7.4-ldap
          - php7.4-zip
          - php7.4-soap
          - php7.4-mbstring
        state: present

    - name: Install Apache, MySQL, and additional PHP modules
      apt:
        name:
          - apache2
          - mysql-client
          - mysql-server
          - libapache2-mod-php
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

    - name: Clone Moodle repository
      git:
        repo: git://git.moodle.org/moodle.git
        dest: /opt/moodle
        version: MOODLE_400_STABLE
        track_submodules: yes

    - name: Copy Moodle to web server directory
      copy:
        src: /opt/moodle
        dest: /var/www/html/moodle
        remote_src: yes

    - name: Create Moodle data directory
      file:
        path: /var/moodledata
        state: directory
        owner: www-data
        group: www-data
        mode: '0777'

    - name: Set permissions for Moodle directory
      file:
        path: /var/www/html/moodle
        state: directory
        mode: '0755'

    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted

    - name: Run the MySQL setup script
      script: bash/mysql.sh

    - name: Set permissions for config.php
      ansible.builtin.shell: sudo chmod -R 777 /var/www/html/moodle
