---
- name: Configure Rsyslog server
  hosts: localhost
  become: yes
  tasks:

    - name: Folder for saving logs
      ansible.builtin.shell: sudo mkdir /var/log/hosts/rsyslog

    - name: Permissions folderlogs
      ansible.builtin.shell: sudo chmod -R 777 /var/log/hosts/rsyslog

    - name: Allow 514/tcp
      ansible.builtin.shell: sudo ufw allow 514/tcp

    - name: Allow 514/udp
      ansible.builtin.shell: sudo ufw allow 514/udp

    - name: Rsyslog configuration
      copy:
        dest: /etc/rsyslog.conf
        content: |
          #################
          #### MODULES ####
          #################

          module(load="imuxsock") # provides support for local system logging
          #module(load="immark")  # provides --MARK-- message capability

          # provides UDP syslog reception
          module(load="imudp")
          input(type="imudp" port="514")

          # provides TCP syslog reception
          module(load="imtcp")
          input(type="imtcp" port="514")

          # provides kernel logging support and enable non-kernel klog messages
          module(load="imklog" permitnonkernelfacility="on")

          ###########################
          #### GLOBAL DIRECTIVES ####
          ###########################

          # Filter duplicated messages
          $RepeatedMsgReduction off

          #
          # Set the default permissions for all log files.
          #
          $FileOwner syslog
          $FileGroup adm
          $FileCreateMode 0640
          $DirCreateMode 0755
          $Umask 0022
          $PrivDropToUser syslog
          $PrivDropToGroup syslog

          #
          # Where to place spool and state files
          #
          $WorkDirectory /var/spool/rsyslog

          #
          # Include all config files in /etc/rsyslog.d/
          #
          $IncludeConfig /etc/rsyslog.d/*.conf

          $template RemoteLogs,"/var/log/hosts/rsyslog/%FROMHOST-IP%/%PROGRAMNAME%.log"
          *.* ?RemoteLogs

    - name: Restart Rsyslog service
      service:
        name: rsyslog
        state: restarted

    - name: Rotating for size
      copy:
        dest: /etc/logrotate.d/rsyslog-custom
        content: |
          /var/log/hosts/rsyslog/*/*.log {
          size 5M
          rotate 1
          nocompress
          nodelaycompress
          missingok
          notifempty
          create 0640 syslog adm
          postrotate
              systemctl restart rsyslog
          endscript
          }

    - name: Add cron job to run logrotate every hour
      cron:
        name: "Run logrotate every hour"
        minute: "*"
        hour: "2"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/usr/sbin/logrotate /etc/logrotate.conf"
        state: present




