---
- name: Installing & configuring Squid
  hosts: [hosts]
  become: true
  tasks:
  - name: upgrade & update apt packages
    ansible.builtin.apt:
      upgrade: true
      update_cache: true
    
  - name: Install squid
    ansible.builtin.apt:
      name: squid
      state: present

  - name: start squid service
    ansible.builtin.systemd_service:
      state: started
      name: squid

  - name: enable squid service
    ansible.builtin.systemd_service:
      name: squid
      enabled: true

  - name: Configure squid -- /etc/squid/squid.conf
    ansible.builtin.lineinfile:
      path: /etc/squid/squid.conf
      line: |  #allow ip-address range / safe-ports
        acl localnet src 192.168.0.0/16 
        acl Safe_ports port 80

  - name: Restart squid -- configurations
    ansible.builtin.systemd_services:
      name: squid
      state: restarted
      daemon_reload: true