---  #sudo ln -s /etc/freeradius/3.0/mods-available/ldap /etc/freeradius/3.0/mods-enabled/
- name: Installing & configuring Radius
  hosts: test
  become: true
  vars:
    radius_server: 10.24.32.190
    ldap_server: '10.24.32.191'

  tasks:
  - name: upgrade & update apt packages
    ansible.builtin.apt:
      upgrade: true
      update_cache: true

  - name: Install freeradius
    ansible.builtin.apt:
      name: freeradius
      state: present

  - name: Install common utils
    ansible.builtin.apt:
      name: freeradius-ldap
      state: present

  - name: Overwrite clients.conf
    template:
      src: /etc/ansible/ansible_inv/templates/clients.conf.j2
      dest: /etc/freeradius/3.0/clients.conf
    become_user: root

  - name: Overwrite ldap
    template:
      src: /etc/ansible/ansible_inv/templates/ldap
      dest: /etc/freeradius/3.0/mods-available/ldap
    become_user: root

  - name: Overwrite default
    template:
      src: /etc/ansible/ansible_inv/templates/default
      dest: /etc/freeradius/3.0/sites-available/default
    become_user: root

  - name: Overwrite inner-tunnel
    template:
      src: /etc/ansible/ansible_inv/templates/inner-tunnel
      dest: /etc/freeradius/3.0/sites-available/inner-tunnel
    become_user: root

  - name: Link the files
    ansible.builtin.shell: sudo ln -s /etc/freeradius/3.0/mods-available/ldap /etc/freeradius/3.0/mods-enabled/
    args:
      executable: /bin/bash
