---
- name: Install NTP chrony server on client
  hosts:
  become: True
  vars:
    server: 10.0.8.12
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Install chrony package
      apt:
        name: chrony
        state: present

    - name: change configuration file
      template:
        src: /templates/chrony-client.conf
        dest: /etc/chrony/chrony.conf

    - name: restart chrony
      ansible.builtin.shell: systemctl restart chrony.service