---
- name: Install Apache, PHP, and LDAP packages
  hosts: test
  become: yes

  tasks:
    - name: Ensure Apache and PHP packages are installed
      apt:
        name:
          - apache2
          - php
          - php-cgi
          - libapache2-mod-php
          - php-mbstring
          - php-common
          - php-pear
        state: present
        update_cache: yes

    - name: Ensure LDAP server and utilities are installed
      apt:
        name:
          - slapd
          - ldap-utils
        state: present
        update_cache: yes

    - name: Ensure LDAP Account Manager is installed
      apt:
        name: ldap-account-manager
        state: present
        update_cache: yes

    - name: Reconfiguring slapd
      ansible.builtin.shell: |
        sudo debconf-set-selections <<< "slapd slapd/password1 password Welkom123"
        sudo debconf-set-selections <<< "slapd slapd/password2 password Welkom123"
        sudo debconf-set-selections <<< "slapd slapd/domain string radius.ijsselstreek-university.nl"
        sudo debconf-set-selections <<< "slapd shared/organization string Hanze"
        sudo debconf-set-selections <<< "slapd slapd/move_old_database boolean true"
        sudo debconf-set-selections <<< "slapd slapd/no_configuration boolean false"
        sudo debconf-set-selections <<< "slapd slapd/purge_database boolean false"
        sudo dpkg-reconfigure slapd --frontend noninteractive
      args:
        executable: /bin/bash
